version: '3'
services:
  nginx:
    image: ${DOCKER_USERNAME}/friends77:latest
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - 80:80
      - 443:443
