export const HOME_CONSTANT = Object.freeze({
  FRIEND_RECOMMENDATION_LIMIT: 8,
  FRIEND_RECOMMENDATION_WITH_INTEREST_CARD_LIMIT: 3,
  FRIEND_RECOMMENDATION_WITH_INTEREST_LIMIT: 6,
  RECOMMENDATION_SIZE_WITH_MULTIPLE_TAGS: 9,
  RECOMMENDATION_SIZE_DEFAULT: 4,
});
