name: Build Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Development
        if: github.base_ref == 'develop'
        run: npm run build:dev

      - name: Build Production
        if: github.base_ref == 'main'
        run: npm run build:prod
