name: Deploy Frontend with Docker

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp tag
        id: timestamp
        run: echo "TAG=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Save SSH key to file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Build and push Docker image
        run: |
          echo $TAG  # TAG 값 확인
          docker build -t ${{ secrets.DOCKER_USERNAME }}/friends77 .
          docker push ${{ secrets.DOCKER_USERNAME }}/friends77
          docker tag ${{ secrets.DOCKER_USERNAME }}/friends77 ${{ secrets.DOCKER_USERNAME }}/friends77:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/friends77:latest

      - name: Deploy to EC2
        run: |
          ssh -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/friends77
            docker stop friends77 || true
            docker rm friends77 || true
            docker run -d -p 80:80 --name friends77 ${{ secrets.DOCKER_USERNAME }}/friends77
          EOF
